var Struct = require('ref-struct');
var Union = require('ref-union');
var ref = require('ref');

exports.CONSTANTS = {
    '': {
        '0': 'PURPLE_STATUS_UNSET',
        '1': 'PURPLE_STATUS_OFFLINE',
        '2': 'PURPLE_STATUS_AVAILABLE',
        '3': 'PURPLE_STATUS_UNAVAILABLE',
        '4': 'PURPLE_STATUS_INVISIBLE',
        '5': 'PURPLE_STATUS_AWAY',
        '6': 'PURPLE_STATUS_EXTENDED_AWAY',
        '7': 'PURPLE_STATUS_MOBILE',
        '8': 'PURPLE_STATUS_TUNE',
        '9': 'PURPLE_STATUS_MOOD',
        '10': 'PURPLE_STATUS_NUM_PRIMITIVES',
        '11': 'PURPLE_CONNECTION_ERROR_CERT_NOT_ACTIVATED',
        '12': 'PURPLE_CONNECTION_ERROR_CERT_HOSTNAME_MISMATCH',
        '13': 'PURPLE_CONNECTION_ERROR_CERT_FINGERPRINT_MISMATCH',
        '14': 'PURPLE_CONNECTION_ERROR_CERT_SELF_SIGNED',
        '15': 'PURPLE_CONNECTION_ERROR_CERT_OTHER_ERROR',
        '16': 'PURPLE_POUNCE_IDLE',
        '17': 'PURPLE_TYPE_BOXED',
        '32': 'PURPLE_POUNCE_IDLE_RETURN',
        '64': 'PURPLE_POUNCE_TYPING',
        '128': 'PURPLE_POUNCE_TYPED',
        '256': 'PURPLE_POUNCE_TYPING_STOPPED',
        '512': 'PURPLE_POUNCE_MESSAGE_RECEIVED',
        '1024': 'PURPLE_MESSAGE_DELAYED',
        '2048': 'PURPLE_MESSAGE_RAW',
        '4096': 'PURPLE_MESSAGE_IMAGES',
        '8192': 'PURPLE_MESSAGE_NOTIFY',
        '16384': 'PURPLE_MESSAGE_NO_LINKIFY',
        '32768': 'PURPLE_MESSAGE_INVISIBLE',
        PURPLE_TYPE_UNKNOWN: 0,
        PURPLE_TYPE_SUBTYPE: 1,
        PURPLE_TYPE_CHAR: 2,
        PURPLE_TYPE_UCHAR: 3,
        PURPLE_TYPE_BOOLEAN: 4,
        PURPLE_TYPE_SHORT: 5,
        PURPLE_TYPE_USHORT: 6,
        PURPLE_TYPE_INT: 7,
        PURPLE_TYPE_UINT: 8,
        PURPLE_TYPE_LONG: 9,
        PURPLE_TYPE_ULONG: 10,
        PURPLE_TYPE_INT64: 11,
        PURPLE_TYPE_UINT64: 12,
        PURPLE_TYPE_STRING: 13,
        PURPLE_TYPE_OBJECT: 14,
        PURPLE_TYPE_POINTER: 15,
        PURPLE_TYPE_ENUM: 16,
        PURPLE_TYPE_BOXED: 17,
        PURPLE_PLUGIN_PREF_NONE: 0,
        PURPLE_PLUGIN_PREF_CHOICE: 1,
        PURPLE_PLUGIN_PREF_INFO: 2,
        PURPLE_PLUGIN_PREF_STRING_FORMAT: 3,
        PURPLE_STRING_FORMAT_TYPE_NONE: 0,
        PURPLE_STRING_FORMAT_TYPE_MULTILINE: 1,
        PURPLE_STRING_FORMAT_TYPE_HTML: 2,
        PURPLE_PLUGIN_UNKNOWN: -1,
        '-1': 'PURPLE_PROXY_USE_GLOBAL',
        PURPLE_PLUGIN_STANDARD: 0,
        PURPLE_PLUGIN_LOADER: 1,
        PURPLE_PLUGIN_PROTOCOL: 2,
        PURPLE_LOG_IM: 0,
        PURPLE_LOG_CHAT: 1,
        PURPLE_LOG_SYSTEM: 2,
        PURPLE_MESSAGE_SEND: 1,
        PURPLE_MESSAGE_RECV: 2,
        PURPLE_MESSAGE_SYSTEM: 4,
        PURPLE_MESSAGE_AUTO_RESP: 8,
        PURPLE_MESSAGE_ACTIVE_ONLY: 16,
        PURPLE_MESSAGE_NICK: 32,
        PURPLE_MESSAGE_NO_LOG: 64,
        PURPLE_MESSAGE_WHISPER: 128,
        PURPLE_MESSAGE_ERROR: 512,
        PURPLE_MESSAGE_DELAYED: 1024,
        PURPLE_MESSAGE_RAW: 2048,
        PURPLE_MESSAGE_IMAGES: 4096,
        PURPLE_MESSAGE_NOTIFY: 8192,
        PURPLE_MESSAGE_NO_LINKIFY: 16384,
        PURPLE_MESSAGE_INVISIBLE: 32768,
        PURPLE_CONV_TYPE_UNKNOWN: 0,
        PURPLE_CONV_TYPE_IM: 1,
        PURPLE_CONV_TYPE_CHAT: 2,
        PURPLE_CONV_TYPE_MISC: 3,
        PURPLE_CONV_TYPE_ANY: 4,
        PURPLE_CONNECTION_HTML: 1,
        PURPLE_CONNECTION_NO_BGCOLOR: 2,
        PURPLE_CONNECTION_AUTO_RESP: 4,
        PURPLE_CONNECTION_FORMATTING_WBFO: 8,
        PURPLE_CONNECTION_NO_NEWLINES: 16,
        PURPLE_CONNECTION_NO_FONTSIZE: 32,
        PURPLE_CONNECTION_NO_URLDESC: 64,
        PURPLE_CONNECTION_NO_IMAGES: 128,
        PURPLE_CONNECTION_ALLOW_CUSTOM_SMILEY: 256,
        PURPLE_CONNECTION_SUPPORT_MOODS: 512,
        PURPLE_CONNECTION_SUPPORT_MOOD_MESSAGES: 1024,
        PURPLE_CONV_UPDATE_ADD: 0,
        PURPLE_CONV_UPDATE_REMOVE: 1,
        PURPLE_CONV_UPDATE_ACCOUNT: 2,
        PURPLE_CONV_UPDATE_TYPING: 3,
        PURPLE_CONV_UPDATE_UNSEEN: 4,
        PURPLE_CONV_UPDATE_LOGGING: 5,
        PURPLE_CONV_UPDATE_TOPIC: 6,
        PURPLE_CONV_ACCOUNT_ONLINE: 7,
        PURPLE_CONV_ACCOUNT_OFFLINE: 8,
        PURPLE_CONV_UPDATE_AWAY: 9,
        PURPLE_CONV_UPDATE_ICON: 10,
        PURPLE_CONV_UPDATE_TITLE: 11,
        PURPLE_CONV_UPDATE_CHATLEFT: 12,
        PURPLE_CONV_UPDATE_FEATURES: 13,
        PURPLE_NOT_TYPING: 0,
        PURPLE_TYPING: 1,
        PURPLE_TYPED: 2,
        PURPLE_CBFLAGS_NONE: 0,
        PURPLE_CBFLAGS_VOICE: 1,
        PURPLE_CBFLAGS_HALFOP: 2,
        PURPLE_CBFLAGS_OP: 4,
        PURPLE_CBFLAGS_FOUNDER: 8,
        PURPLE_CBFLAGS_TYPING: 16,
        PURPLE_CBFLAGS_AWAY: 32,
        PURPLE_XFER_UNKNOWN: 0,
        PURPLE_XFER_SEND: 1,
        PURPLE_XFER_RECEIVE: 2,
        PURPLE_XFER_STATUS_UNKNOWN: 0,
        PURPLE_XFER_STATUS_NOT_STARTED: 1,
        PURPLE_XFER_STATUS_ACCEPTED: 2,
        PURPLE_XFER_STATUS_STARTED: 3,
        PURPLE_XFER_STATUS_DONE: 4,
        PURPLE_XFER_STATUS_CANCEL_LOCAL: 5,
        PURPLE_XFER_STATUS_CANCEL_REMOTE: 6,
        PURPLE_MEDIA_CANDIDATE_TYPE_HOST: 0,
        PURPLE_MEDIA_CANDIDATE_TYPE_SRFLX: 1,
        PURPLE_MEDIA_CANDIDATE_TYPE_PRFLX: 2,
        PURPLE_MEDIA_CANDIDATE_TYPE_RELAY: 3,
        PURPLE_MEDIA_CANDIDATE_TYPE_MULTICAST: 4,
        PURPLE_MEDIA_NETWORK_PROTOCOL_UDP: 0,
        PURPLE_MEDIA_NETWORK_PROTOCOL_TCP: 1,
        PURPLE_NOTIFY_BUTTON_LABELED: 0,
        PURPLE_NOTIFY_BUTTON_CONTINUE: 1,
        PURPLE_NOTIFY_BUTTON_ADD: 2,
        PURPLE_NOTIFY_BUTTON_INFO: 3,
        PURPLE_NOTIFY_BUTTON_IM: 4,
        PURPLE_NOTIFY_BUTTON_JOIN: 5,
        PURPLE_NOTIFY_BUTTON_INVITE: 6,
        PURPLE_NOTIFY_MSG_ERROR: 0,
        PURPLE_NOTIFY_MSG_WARNING: 1,
        PURPLE_NOTIFY_MSG_INFO: 2,
        PURPLE_NOTIFY_USER_INFO_ENTRY_PAIR: 0,
        PURPLE_NOTIFY_USER_INFO_ENTRY_SECTION_BREAK: 1,
        PURPLE_NOTIFY_USER_INFO_ENTRY_SECTION_HEADER: 2,
        PURPLE_NOTIFY_MESSAGE: 0,
        PURPLE_NOTIFY_EMAIL: 1,
        PURPLE_NOTIFY_EMAILS: 2,
        PURPLE_NOTIFY_FORMATTED: 3,
        PURPLE_NOTIFY_SEARCHRESULTS: 4,
        PURPLE_NOTIFY_USERINFO: 5,
        PURPLE_NOTIFY_URI: 6,
        PURPLE_MEDIA_NONE: 0,
        PURPLE_MEDIA_RECV_AUDIO: 1,
        PURPLE_MEDIA_SEND_AUDIO: 2,
        PURPLE_MEDIA_RECV_VIDEO: 4,
        PURPLE_MEDIA_SEND_VIDEO: 8,
        PURPLE_MEDIA_AUDIO: 3,
        PURPLE_MEDIA_VIDEO: 12,
        PURPLE_MEDIA_INFO_HANGUP: 0,
        PURPLE_MEDIA_INFO_ACCEPT: 1,
        PURPLE_MEDIA_INFO_REJECT: 2,
        PURPLE_MEDIA_INFO_MUTE: 3,
        PURPLE_MEDIA_INFO_UNMUTE: 4,
        PURPLE_MEDIA_INFO_PAUSE: 5,
        PURPLE_MEDIA_INFO_UNPAUSE: 6,
        PURPLE_MEDIA_INFO_HOLD: 7,
        PURPLE_MEDIA_INFO_UNHOLD: 8,
        PURPLE_INPUT_READ: 1,
        PURPLE_INPUT_WRITE: 2,
        PURPLE_PROXY_USE_GLOBAL: -1,
        PURPLE_PROXY_NONE: 0,
        PURPLE_PROXY_HTTP: 1,
        PURPLE_PROXY_SOCKS4: 2,
        PURPLE_PROXY_SOCKS5: 3,
        PURPLE_PROXY_USE_ENVVAR: 4,
        PURPLE_PROXY_TOR: 5,
        PURPLE_ROOMLIST_ROOMTYPE_CATEGORY: 1,
        PURPLE_ROOMLIST_ROOMTYPE_ROOM: 2,
        PURPLE_ROOMLIST_FIELD_BOOL: 0,
        PURPLE_ROOMLIST_FIELD_INT: 1,
        PURPLE_ROOMLIST_FIELD_STRING: 2,
        PURPLE_MEDIA_CAPS_NONE: 0,
        PURPLE_MEDIA_CAPS_AUDIO: 1,
        PURPLE_MEDIA_CAPS_AUDIO_SINGLE_DIRECTION: 2,
        PURPLE_MEDIA_CAPS_VIDEO: 4,
        PURPLE_MEDIA_CAPS_VIDEO_SINGLE_DIRECTION: 8,
        PURPLE_MEDIA_CAPS_AUDIO_VIDEO: 16,
        PURPLE_MEDIA_CAPS_MODIFY_SESSION: 32,
        PURPLE_MEDIA_CAPS_CHANGE_DIRECTION: 64,
        PURPLE_BLIST_NODE_FLAG_NO_SAVE: 1,
        PURPLE_BLIST_GROUP_NODE: 0,
        PURPLE_BLIST_CONTACT_NODE: 1,
        PURPLE_BLIST_BUDDY_NODE: 2,
        PURPLE_BLIST_CHAT_NODE: 3,
        PURPLE_BLIST_OTHER_NODE: 4,
        PURPLE_PRESENCE_CONTEXT_UNSET: 0,
        PURPLE_PRESENCE_CONTEXT_ACCOUNT: 1,
        PURPLE_PRESENCE_CONTEXT_CONV: 2,
        PURPLE_PRESENCE_CONTEXT_BUDDY: 3,
        PURPLE_CERTIFICATE_INVALID: 0,
        PURPLE_CERTIFICATE_VALID: 1,
        PURPLE_SSL_HANDSHAKE_FAILED: 1,
        PURPLE_SSL_CONNECT_FAILED: 2,
        PURPLE_SSL_CERTIFICATE_INVALID: 3,
        PURPLE_DISCONNECTED: 0,
        PURPLE_CONNECTED: 1,
        PURPLE_CONNECTING: 2,
        PURPLE_CONNECTION_ERROR_NETWORK_ERROR: 0,
        PURPLE_CONNECTION_ERROR_INVALID_USERNAME: 1,
        PURPLE_CONNECTION_ERROR_AUTHENTICATION_FAILED: 2,
        PURPLE_CONNECTION_ERROR_AUTHENTICATION_IMPOSSIBLE: 3,
        PURPLE_CONNECTION_ERROR_NO_SSL_SUPPORT: 4,
        PURPLE_CONNECTION_ERROR_ENCRYPTION_ERROR: 5,
        PURPLE_CONNECTION_ERROR_NAME_IN_USE: 6,
        PURPLE_CONNECTION_ERROR_INVALID_SETTINGS: 7,
        PURPLE_CONNECTION_ERROR_CERT_NOT_PROVIDED: 8,
        PURPLE_CONNECTION_ERROR_CERT_UNTRUSTED: 9,
        PURPLE_CONNECTION_ERROR_CERT_EXPIRED: 10,
        PURPLE_CONNECTION_ERROR_CERT_NOT_ACTIVATED: 11,
        PURPLE_CONNECTION_ERROR_CERT_HOSTNAME_MISMATCH: 12,
        PURPLE_CONNECTION_ERROR_CERT_FINGERPRINT_MISMATCH: 13,
        PURPLE_CONNECTION_ERROR_CERT_SELF_SIGNED: 14,
        PURPLE_CONNECTION_ERROR_CERT_OTHER_ERROR: 15,
        PURPLE_CONNECTION_ERROR_OTHER_ERROR: 16,
        PURPLE_DEBUG_ALL: 0,
        PURPLE_DEBUG_MISC: 1,
        PURPLE_DEBUG_INFO: 2,
        PURPLE_DEBUG_WARNING: 3,
        PURPLE_DEBUG_ERROR: 4,
        PURPLE_DEBUG_FATAL: 5,
        PURPLE_DESKTOP_ITEM_TYPE_NULL: 0,
        PURPLE_DESKTOP_ITEM_TYPE_OTHER: 1,
        PURPLE_DESKTOP_ITEM_TYPE_APPLICATION: 2,
        PURPLE_DESKTOP_ITEM_TYPE_LINK: 3,
        PURPLE_DESKTOP_ITEM_TYPE_FSDEVICE: 4,
        PURPLE_DESKTOP_ITEM_TYPE_MIME_TYPE: 5,
        PURPLE_DESKTOP_ITEM_TYPE_DIRECTORY: 6,
        PURPLE_DESKTOP_ITEM_TYPE_SERVICE: 7,
        PURPLE_DESKTOP_ITEM_TYPE_SERVICE_TYPE: 8,
        PURPLE_PMP_TYPE_UDP: 0,
        PURPLE_PMP_TYPE_TCP: 1,
        PURPLE_POUNCE_NONE: 0,
        PURPLE_POUNCE_SIGNON: 1,
        PURPLE_POUNCE_SIGNOFF: 2,
        PURPLE_POUNCE_AWAY: 4,
        PURPLE_POUNCE_AWAY_RETURN: 8,
        PURPLE_POUNCE_IDLE: 16,
        PURPLE_POUNCE_IDLE_RETURN: 32,
        PURPLE_POUNCE_TYPING: 64,
        PURPLE_POUNCE_TYPED: 128,
        PURPLE_POUNCE_TYPING_STOPPED: 256,
        PURPLE_POUNCE_MESSAGE_RECEIVED: 512,
        PURPLE_POUNCE_OPTION_NONE: 0,
        PURPLE_POUNCE_OPTION_AWAY: 1,
        PURPLE_REQUEST_FIELD_NONE: 0,
        PURPLE_REQUEST_FIELD_STRING: 1,
        PURPLE_REQUEST_FIELD_INTEGER: 2,
        PURPLE_REQUEST_FIELD_BOOLEAN: 3,
        PURPLE_REQUEST_FIELD_CHOICE: 4,
        PURPLE_REQUEST_FIELD_LIST: 5,
        PURPLE_REQUEST_FIELD_LABEL: 6,
        PURPLE_REQUEST_FIELD_IMAGE: 7,
        PURPLE_REQUEST_FIELD_ACCOUNT: 8,
        PURPLE_REQUEST_INPUT: 0,
        PURPLE_REQUEST_CHOICE: 1,
        PURPLE_REQUEST_ACTION: 2,
        PURPLE_REQUEST_FIELDS: 3,
        PURPLE_REQUEST_FILE: 4,
        PURPLE_REQUEST_FOLDER: 5
    },
    _PurplePrefType: {
        '0': 'PURPLE_PREF_NONE',
        '1': 'PURPLE_PREF_BOOLEAN',
        '2': 'PURPLE_PREF_INT',
        '3': 'PURPLE_PREF_STRING',
        '4': 'PURPLE_PREF_STRING_LIST',
        '5': 'PURPLE_PREF_PATH',
        '6': 'PURPLE_PREF_PATH_LIST',
        PURPLE_PREF_NONE: 0,
        PURPLE_PREF_BOOLEAN: 1,
        PURPLE_PREF_INT: 2,
        PURPLE_PREF_STRING: 3,
        PURPLE_PREF_STRING_LIST: 4,
        PURPLE_PREF_PATH: 5,
        PURPLE_PREF_PATH_LIST: 6
    },
    _PurplePrivacyType: {
        '1': 'PURPLE_PRIVACY_ALLOW_ALL',
        '2': 'PURPLE_PRIVACY_DENY_ALL',
        '3': 'PURPLE_PRIVACY_ALLOW_USERS',
        '4': 'PURPLE_PRIVACY_DENY_USERS',
        '5': 'PURPLE_PRIVACY_ALLOW_BUDDYLIST',
        PURPLE_PRIVACY_ALLOW_ALL: 1,
        PURPLE_PRIVACY_DENY_ALL: 2,
        PURPLE_PRIVACY_ALLOW_USERS: 3,
        PURPLE_PRIVACY_DENY_USERS: 4,
        PURPLE_PRIVACY_ALLOW_BUDDYLIST: 5
    },
    _PurpleCipherBatchMode: {
        '0': 'PURPLE_CIPHER_BATCH_MODE_ECB',
        '1': 'PURPLE_CIPHER_BATCH_MODE_CBC',
        PURPLE_CIPHER_BATCH_MODE_ECB: 0,
        PURPLE_CIPHER_BATCH_MODE_CBC: 1
    },
    _PurpleCmdPriority: {
        '0': 'PURPLE_CMD_P_LOW',
        '1000': 'PURPLE_CMD_P_DEFAULT',
        '2000': 'PURPLE_CMD_P_PRPL',
        '3000': 'PURPLE_CMD_P_PLUGIN',
        '4000': 'PURPLE_CMD_P_ALIAS',
        '5000': 'PURPLE_CMD_P_HIGH',
        '6000': 'PURPLE_CMD_P_VERY_HIGH',
        PURPLE_CMD_P_VERY_LOW: -1000,
        '-1000': 'PURPLE_CMD_P_VERY_LOW',
        PURPLE_CMD_P_LOW: 0,
        PURPLE_CMD_P_DEFAULT: 1000,
        PURPLE_CMD_P_PRPL: 2000,
        PURPLE_CMD_P_PLUGIN: 3000,
        PURPLE_CMD_P_ALIAS: 4000,
        PURPLE_CMD_P_HIGH: 5000,
        PURPLE_CMD_P_VERY_HIGH: 6000
    },
    _PurpleCmdFlag: {
        '1': 'PURPLE_CMD_FLAG_IM',
        '2': 'PURPLE_CMD_FLAG_CHAT',
        '4': 'PURPLE_CMD_FLAG_PRPL_ONLY',
        '8': 'PURPLE_CMD_FLAG_ALLOW_WRONG_ARGS',
        PURPLE_CMD_FLAG_IM: 1,
        PURPLE_CMD_FLAG_CHAT: 2,
        PURPLE_CMD_FLAG_PRPL_ONLY: 4,
        PURPLE_CMD_FLAG_ALLOW_WRONG_ARGS: 8
    },
    _PurpleCmdStatus: {
        '0': 'PURPLE_CMD_STATUS_OK',
        '1': 'PURPLE_CMD_STATUS_FAILED',
        '2': 'PURPLE_CMD_STATUS_NOT_FOUND',
        '3': 'PURPLE_CMD_STATUS_WRONG_ARGS',
        '4': 'PURPLE_CMD_STATUS_WRONG_PRPL',
        '5': 'PURPLE_CMD_STATUS_WRONG_TYPE',
        PURPLE_CMD_STATUS_OK: 0,
        PURPLE_CMD_STATUS_FAILED: 1,
        PURPLE_CMD_STATUS_NOT_FOUND: 2,
        PURPLE_CMD_STATUS_WRONG_ARGS: 3,
        PURPLE_CMD_STATUS_WRONG_PRPL: 4,
        PURPLE_CMD_STATUS_WRONG_TYPE: 5
    },
    _PurpleSoundEventID: {
        '0': 'PURPLE_SOUND_BUDDY_ARRIVE',
        '1': 'PURPLE_SOUND_BUDDY_LEAVE',
        '2': 'PURPLE_SOUND_RECEIVE',
        '3': 'PURPLE_SOUND_FIRST_RECEIVE',
        '4': 'PURPLE_SOUND_SEND',
        '5': 'PURPLE_SOUND_CHAT_JOIN',
        '6': 'PURPLE_SOUND_CHAT_LEAVE',
        '7': 'PURPLE_SOUND_CHAT_YOU_SAY',
        '8': 'PURPLE_SOUND_CHAT_SAY',
        '9': 'PURPLE_SOUND_POUNCE_DEFAULT',
        '10': 'PURPLE_SOUND_CHAT_NICK',
        '11': 'PURPLE_SOUND_GOT_ATTENTION',
        '12': 'PURPLE_NUM_SOUNDS',
        PURPLE_SOUND_BUDDY_ARRIVE: 0,
        PURPLE_SOUND_BUDDY_LEAVE: 1,
        PURPLE_SOUND_RECEIVE: 2,
        PURPLE_SOUND_FIRST_RECEIVE: 3,
        PURPLE_SOUND_SEND: 4,
        PURPLE_SOUND_CHAT_JOIN: 5,
        PURPLE_SOUND_CHAT_LEAVE: 6,
        PURPLE_SOUND_CHAT_YOU_SAY: 7,
        PURPLE_SOUND_CHAT_SAY: 8,
        PURPLE_SOUND_POUNCE_DEFAULT: 9,
        PURPLE_SOUND_CHAT_NICK: 10,
        PURPLE_SOUND_GOT_ATTENTION: 11,
        PURPLE_NUM_SOUNDS: 12
    }
};
var __va_list_tag = exports.__va_list_tag = Struct([
    ['uint32', 'gp_offset'],
    ['uint32', 'fp_offset'],
    ['pointer', 'overflow_arg_area'],
    ['pointer', 'reg_save_area'], ]);
var __va_list_tagPtr = exports.__va_list_tagPtr = ref.refType(__va_list_tag);
var PurpleLogReadFlags = exports.PurpleLogReadFlags = Struct([
    ['int32', 'PURPLE_LOG_READ_NO_NEWLINE'], ]);
var PurpleLogReadFlagsPtr = exports.PurpleLogReadFlagsPtr = ref.refType(PurpleLogReadFlags);
var PurpleXferUiOps = exports.PurpleXferUiOps = Struct([
    ['pointer', 'new_xfer'],
    ['pointer', 'destroy'],
    ['pointer', 'add_xfer'],
    ['pointer', 'update_progress'],
    ['pointer', 'cancel_local'],
    ['pointer', 'cancel_remote'],
    ['pointer', 'ui_write'],
    ['pointer', 'ui_read'],
    ['pointer', 'data_not_sent'],
    ['pointer', 'add_thumbnail'], ]);
var PurpleXferUiOpsPtr = exports.PurpleXferUiOpsPtr = ref.refType(PurpleXferUiOps);
var PurpleNotifySearchResults = exports.PurpleNotifySearchResults = Struct([
    ['pointer', 'columns'],
    ['pointer', 'rows'],
    ['pointer', 'buttons'], ]);
var PurpleNotifySearchResultsPtr = exports.PurpleNotifySearchResultsPtr = ref.refType(PurpleNotifySearchResults);
var PurpleNotifySearchColumn = exports.PurpleNotifySearchColumn = Struct([
    ['string', 'title'], ]);
var PurpleNotifySearchColumnPtr = exports.PurpleNotifySearchColumnPtr = ref.refType(PurpleNotifySearchColumn);
var PurpleNotifyUiOps = exports.PurpleNotifyUiOps = Struct([
    ['pointer', 'notify_message'],
    ['pointer', 'notify_email'],
    ['pointer', 'notify_emails'],
    ['pointer', 'notify_formatted'],
    ['pointer', 'notify_searchresults'],
    ['pointer', 'notify_searchresults_new_rows'],
    ['pointer', 'notify_userinfo'],
    ['pointer', 'notify_uri'],
    ['pointer', 'close_notify'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleNotifyUiOpsPtr = exports.PurpleNotifyUiOpsPtr = ref.refType(PurpleNotifyUiOps);
var PurpleProxyInfo = exports.PurpleProxyInfo = Struct([
    ['int32', 'type'],
    ['string', 'host'],
    ['int32', 'port'],
    ['string', 'username'],
    ['string', 'password'], ]);
var PurpleProxyInfoPtr = exports.PurpleProxyInfoPtr = ref.refType(PurpleProxyInfo);
var PurpleWhiteboardUiOps = exports.PurpleWhiteboardUiOps = Struct([
    ['pointer', 'create'],
    ['pointer', 'destroy'],
    ['pointer', 'set_dimensions'],
    ['pointer', 'set_brush'],
    ['pointer', 'draw_point'],
    ['pointer', 'draw_line'],
    ['pointer', 'clear'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleWhiteboardUiOpsPtr = exports.PurpleWhiteboardUiOpsPtr = ref.refType(PurpleWhiteboardUiOps);
var PurpleWhiteboard = exports.PurpleWhiteboard = Struct([
    ['int32', 'state'],
    ['pointer', 'account'],
    ['string', 'who'],
    ['pointer', 'ui_data'],
    ['pointer', 'proto_data'],
    ['pointer', 'prpl_ops'],
    ['pointer', 'draw_list'], ]);
var PurpleWhiteboardPtr = exports.PurpleWhiteboardPtr = ref.refType(PurpleWhiteboard);
var PurpleSslOps = exports.PurpleSslOps = Struct([
    ['pointer', 'init'],
    ['pointer', 'uninit'],
    ['pointer', 'connectfunc'],
    ['pointer', 'close'],
    ['pointer', 'read'],
    ['pointer', 'write'],
    ['pointer', 'get_peer_certificates'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleSslOpsPtr = exports.PurpleSslOpsPtr = ref.refType(PurpleSslOps);
var PurpleConnectionUiOps = exports.PurpleConnectionUiOps = Struct([
    ['pointer', 'connect_progress'],
    ['pointer', 'connected'],
    ['pointer', 'disconnected'],
    ['pointer', 'notice'],
    ['pointer', 'report_disconnect'],
    ['pointer', 'network_connected'],
    ['pointer', 'network_disconnected'],
    ['pointer', 'report_disconnect_reason'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'], ]);
var PurpleConnectionUiOpsPtr = exports.PurpleConnectionUiOpsPtr = ref.refType(PurpleConnectionUiOps);
var PurplePrivacyUiOps = exports.PurplePrivacyUiOps = Struct([
    ['pointer', 'permit_added'],
    ['pointer', 'permit_removed'],
    ['pointer', 'deny_added'],
    ['pointer', 'deny_removed'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurplePrivacyUiOpsPtr = exports.PurplePrivacyUiOpsPtr = ref.refType(PurplePrivacyUiOps);
var PurpleConnectionErrorInfo = exports.PurpleConnectionErrorInfo = Struct([
    ['uint32', 'type'],
    ['string', 'description'], ]);
var PurpleConnectionErrorInfoPtr = exports.PurpleConnectionErrorInfoPtr = ref.refType(PurpleConnectionErrorInfo);
var PurpleAccountUserSplit = exports.PurpleAccountUserSplit = Struct([
    ['string', 'text'],
    ['string', 'default_value'],
    ['char', 'field_sep'],
    ['int32', 'reverse'], ]);
var PurpleAccountUserSplitPtr = exports.PurpleAccountUserSplitPtr = ref.refType(PurpleAccountUserSplit);
var PurpleCircBuffer = exports.PurpleCircBuffer = Struct([
    ['pointer', 'buffer'],
    ['ulong', 'growsize'],
    ['ulong', 'buflen'],
    ['ulong', 'bufused'],
    ['pointer', 'inptr'],
    ['pointer', 'outptr'], ]);
var PurpleCircBufferPtr = exports.PurpleCircBufferPtr = ref.refType(PurpleCircBuffer);
var PurpleCoreUiOps = exports.PurpleCoreUiOps = Struct([
    ['pointer', 'ui_prefs_init'],
    ['pointer', 'debug_ui_init'],
    ['pointer', 'ui_init'],
    ['pointer', 'quit'],
    ['pointer', 'get_ui_info'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'], ]);
var PurpleCoreUiOpsPtr = exports.PurpleCoreUiOpsPtr = ref.refType(PurpleCoreUiOps);
var PurpleDebugUiOps = exports.PurpleDebugUiOps = Struct([
    ['pointer', 'print'],
    ['pointer', 'is_enabled'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleDebugUiOpsPtr = exports.PurpleDebugUiOpsPtr = ref.refType(PurpleDebugUiOps);
var PurpleDnsQueryUiOps = exports.PurpleDnsQueryUiOps = Struct([
    ['pointer', 'resolve_host'],
    ['pointer', 'destroy'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleDnsQueryUiOpsPtr = exports.PurpleDnsQueryUiOpsPtr = ref.refType(PurpleDnsQueryUiOps);
var PurpleSrvTxtQueryUiOps = exports.PurpleSrvTxtQueryUiOps = Struct([
    ['pointer', 'resolve'],
    ['pointer', 'destroy'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleSrvTxtQueryUiOpsPtr = exports.PurpleSrvTxtQueryUiOpsPtr = ref.refType(PurpleSrvTxtQueryUiOps);
var PurpleIdleUiOps = exports.PurpleIdleUiOps = Struct([
    ['pointer', 'get_time_idle'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleIdleUiOpsPtr = exports.PurpleIdleUiOpsPtr = ref.refType(PurpleIdleUiOps);
var PurpleRequestFields = exports.PurpleRequestFields = Struct([
    ['pointer', 'groups'],
    ['pointer', 'fields'],
    ['pointer', 'required_fields'],
    ['pointer', 'ui_data'], ]);
var PurpleRequestFieldsPtr = exports.PurpleRequestFieldsPtr = ref.refType(PurpleRequestFields);
var PurpleRequestFieldGroup = exports.PurpleRequestFieldGroup = Struct([
    [PurpleRequestFieldsPtr, 'fields_list'],
    ['string', 'title'],
    ['pointer', 'fields'], ]);
var PurpleRequestFieldGroupPtr = exports.PurpleRequestFieldGroupPtr = ref.refType(PurpleRequestFieldGroup);
var PurpleRequestUiOps = exports.PurpleRequestUiOps = Struct([
    ['pointer', 'request_input'],
    ['pointer', 'request_choice'],
    ['pointer', 'request_action'],
    ['pointer', 'request_fields'],
    ['pointer', 'request_file'],
    ['pointer', 'close_request'],
    ['pointer', 'request_folder'],
    ['pointer', 'request_action_with_icon'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'], ]);
var PurpleRequestUiOpsPtr = exports.PurpleRequestUiOpsPtr = ref.refType(PurpleRequestUiOps);
var PurpleSoundUiOps = exports.PurpleSoundUiOps = Struct([
    ['pointer', 'init'],
    ['pointer', 'uninit'],
    ['pointer', 'play_file'],
    ['pointer', 'play_event'],
    ['pointer', '_purple_reserved1'],
    ['pointer', '_purple_reserved2'],
    ['pointer', '_purple_reserved3'],
    ['pointer', '_purple_reserved4'], ]);
var PurpleSoundUiOpsPtr = exports.PurpleSoundUiOpsPtr = ref.refType(PurpleSoundUiOps);


var GListPtrGeneric = exports.GListPtrGeneric = function(gtype) {
  var list = Struct({ data: gtype });
  var list_ptr = ref.refType(list);
  list.defineProperty('next', list_ptr);
  list.defineProperty('prev', list_ptr);
  return list_ptr;
};


var PurpleEventLoopUiOps = exports.PurpleEventLoopUiOps = Struct({
  timeout_add: ref.refType(ref.types.void),
  timeout_remove: ref.refType(ref.types.void),
  input_add: ref.refType(ref.types.void),
  input_remove: ref.refType(ref.types.void),
  input_get_error: ref.refType(ref.types.void),
  timeout_add_seconds: ref.refType(ref.types.void),
  reserved_1: ref.refType(ref.types.void),
  reserved_2: ref.refType(ref.types.void),
  reserved_3: ref.refType(ref.types.void),
});
var PurpleEventLoopUiOpsPtr = exports.PurpleEventLoopUiOpsPtr = ref.refType(PurpleEventLoopUiOps);
var GList = exports.GList = Struct({ data: ref.refType(ref.types.void) });
var GListPtr = exports.GListPtr = ref.refType(GList);
GList.defineProperty('next', GListPtr);
GList.defineProperty('prev', GListPtr);
var ptrType = ref.refType(ref.types.void);

var PurpleAccountOption = exports.PurpleAccountOption = Struct({
  type: ref.types.uint32,
  text: ref.types.CString,
  pref_name: ref.types.CString,
  default_value: Union({
    boolean: ref.types.uint32,
    integer: ref.types.int32,
    string: ref.types.CString,
    list: GListPtr,
  }),
  masked: ref.types.uint32,
});
var PurpleAccountOptionPtr = exports.PurpleAccountOptionPtr = ref.refType(PurpleAccountOption);

var PurplePluginProtocolInfo = exports.PurplePluginProtocolInfo = Struct({
  options: ref.types.uint32,
  user_splits: GListPtr,
  protocol_options: GListPtrGeneric(PurpleAccountOptionPtr),
  // TODO XXX FIXME finish definition
});
var PurplePluginProtocolInfoPtr = exports.PurplePluginProtocolInfoPtr = ref.refType(PurplePluginProtocolInfo);

var PurplePluginInfo = exports.PurplePluginInfo = Struct({
  magic: ref.types.uint32,
  major_version: ref.types.uint32,
  minor_version: ref.types.uint32,
  type: ref.types.int32,
  ui_requirement: ref.types.CString,
  flags: ref.types.ulong,
  dependencies: GListPtr,
  priority: ref.types.int32,
  id: ref.types.CString,
  name: ref.types.CString,
  version: ref.types.CString,
  summary: ref.types.CString,
  description: ref.types.CString,
  author: ref.types.CString,
  homepage: ref.types.CString,
  load: ptrType,
  unload: ptrType,
  destroy: ptrType,
  ui_info: ptrType,
  extra_info: PurplePluginProtocolInfoPtr,
  prefs_info: ptrType,
  actions: ptrType,
  reserved_1: ptrType,
  reserved_2: ptrType,
  reserved_3: ptrType,
  reserved_4: ptrType,
});
var PurplePluginInfoPtr = exports.PurplePluginInfoPtr = ref.refType(PurplePluginInfo);

var PurplePlugin = exports.PurplePlugin = Struct({
  native_plugin: ref.types.uint32,
  loaded: ref.types.uint32,
  handle: ptrType,
  path: ref.types.CString,
  info: PurplePluginInfoPtr,
  error: ref.types.CString,
  ipc_data: ptrType,
  extra: ptrType,
  unloadable: ref.types.uint32,
  dependent_plugins: ptrType,
  reserved_1: ptrType,
  reserved_2: ptrType,
  reserved_3: ptrType,
  reserved_4: ptrType,
});
var PurplePluginPtr = exports.PurplePluginPtr = ref.refType(PurplePlugin);

var PurpleConversationUiOps = exports.PurpleConversationUiOps = Struct({
  create_conversation: ptrType,
  destroy_conversation: ptrType,
  write_chat: ptrType,
  write_im: ptrType,
  write_conv: ptrType,
  chat_add_users: ptrType,
  chat_rename_user: ptrType,
  chat_remove_users: ptrType,
  chat_update_user: ptrType,
  present: ptrType,
  has_focus: ptrType,
  custom_smiley_add: ptrType,
  custom_smiley_write: ptrType,
  custom_smiley_close: ptrType,
  send_confirm: ptrType,
  reserved_1: ptrType,
  reserved_2: ptrType,
  reserved_3: ptrType,
  reserved_4: ptrType,
});
var PurpleConversationUiOpsPtr = exports.PurpleConversationUiOpsPtr = ref.refType(PurpleConversationUiOps);
